[package]
name = "rmsd"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
clap = { version = "4.5.17", features = ["derive"] }
rusb = "0.9.4"
serde = { version = "1.0.209", features = ["derive"] }
